name: credit_risk_model
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9
  
  # Core scientific packages
  - numpy=1.24.3
  - pandas=2.1.3
  - scikit-learn=1.3.2
  
  # Deep Learning
  - tensorflow=2.15.0
  - tensorflow-gpu=2.15.0  # Comment out if not using GPU
  - cudatoolkit=11.8      # Comment out if not using GPU
  - cudnn=8.9.2          # Comment out if not using GPU
  
  # Visualization
  - matplotlib=3.8.2
  - seaborn=0.13.0
  
  # Development tools
  - jupyter=1.0.0
  - jupyterlab=4.0.9
  - pytest=7.4.3
  - black=23.11.0
  - flake8=6.1.0
  
  # Additional conda packages
  - pip=23.0
  - nodejs>=18  # For JupyterLab extensions
  
  # Install remaining packages via pip
  - pip:
    # Install the package in editable mode with all extras
    - -e .[api,viz,dev,docs]
    
    # Core ML packages
    - keras-tuner==1.4.6
    - silence-tensorflow==1.2.1
    - mlflow==2.9.0
    
    # API packages
    - flask==3.0.0
    - flask-cors==4.0.0
    - flask-limiter==3.5.0
    - prometheus-client==0.19.0
    
    # Development packages
    - pytest-cov==4.1.0
    - pre-commit==3.5.0
    - mypy==1.7.1 