name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install a linter (e.g., flake8)
      #- name: Install linter
      #  run: pip install flake8

      # Run linting
      #- name: Lint with flake8
      #  run: |
      #    flake8 . --max-line-length=120 --exclude=venv,mlruns,hyperparameter_tuning

      # Install pytest for running tests
      - name: Install pytest
        run: pip install pytest

      # Debug directory structure and Python path
      - name: Debug environment
        run: |
          pwd  # Should print /home/runner/work/credit-card-risk-model/credit-card-risk-model/
          ls -R  # List directory structure
          python -c "import sys; print(sys.path)"  # Print Python module search path

      # Run tests
      - name: Run tests
        run: pytest tests/ -v

      # Cache MLflow artifacts (optional)
      - name: Cache MLflow artifacts
        uses: actions/cache@v3
        with:
          path: mlruns/
          key: ${{ runner.os }}-mlflow-${{ hashFiles('**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-mlflow-

      # Run the main script (optional, limited execution for CI)
      - name: Run main script (limited epochs)
        run: python main.py
        env:
          EPOCHS_OVERRIDE: 2