name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov black isort
        pip install -r credit_risk_model/requirements.txt
    
    - name: Check code formatting with Black
      run: |
        black --check credit_risk_model/src
    
    - name: Check import sorting with isort
      run: |
        isort --check-only credit_risk_model/src
    
    - name: Lint with flake8
      run: |
        flake8 credit_risk_model/src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 credit_risk_model/src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run unit tests with pytest
      run: |
        pytest credit_risk_model/tests --cov=credit_risk_model/src --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 